### PR TITLE
Fixed some failures when applying some CPU settings

### PR DESCRIPTION
**Pull request by ischeinkman**
Fixed some crashes I encountered when writing CPU settings, all related to missing files located under per-CPU-core directories in sysfs. 

Namely: 
* Not all paths matching `/sys/devices/system/cpu/cpu*` are CPU-core directories. In my system I also have a `/sys/devices/system/cpu/cpufreq` and `/sys/devices/system/cpu/cpuidle` at the top level. This means that the wildcard `echo` calls would crash.
* Not all cores can be toggled online/offline. For example on my Framework `cpu0` is missing that option entirely (but not the rest of them).

### CODE REVIEW

**Comment by ischeinkman** [comment]
Should I also add in checks for governor, min freq, and max freq? I basically only did what I needed to prevent crashes on my system (in addition to switching `run_command` to using `sh` instead of `zsh` -- is there a reason this needs `zsh` specifically?)

**Comment by TheAlexDev23** [comment]
That's weird, if a shell command fails the program shouldn't crash. Or did you just receive an output message in the logs without any crash?

I didn't add checks for whether some paths exist because I start a shell, and if there are issues, those will fail within the shell. So that's why profile.rs is structured that way, if it fails then ignore it and continue onto the next setting (except, of course, the parts where something failing requires extra behavior). Adding extra checks could provide more verbose warnings without changing the actual behavior but will require a LOT of changes, pretty much for every single shell command for proper consistency in the source code.

As per why zsh is used, that's because output redirection and wildcard expansion didn't work in bash/sh. For some reason `echo X > /sys/some/*/path` only works in zsh and not any other shell, at least from my testing.

**Comment by TheAlexDev23** [comment]
As per the wildcard expansion failing, that's a nice catch. I don't know how I missed that before.

**Comment by ischeinkman** [comment]
Hey sorry for the delay, got a bit busy with personal stuff. 

> That's weird, if a shell command fails the program shouldn't crash. Or did you just receive an output message in the logs without any crash?

I saw an error followed by a crash in the logs. This patch removed both the error and stopped the crash. I'm not 100% sure why this stopped the crashes, to be fair; I wonder if there's a weird subprocess interaction going on (maybe with systemd)? 

> I didn't add checks for whether some paths exist because I start a shell, and if there are issues, those will fail within the shell. So that's why profile.rs is structured that way, if it fails then ignore it and continue onto the next setting (except, of course, the parts where something failing requires extra behavior). Adding extra checks could provide more verbose warnings without changing the actual behavior but will require a LOT of changes, pretty much for every single shell command for proper consistency in the source code.

Would it be worth pulling out the "write a value to a file" case into a separate method without requiring a subshell? This would help detect "file not existing" errors and keep the code cleaner in general (by not building bash strings and invoking subprocesses for writing files). I can work on this if you'd be okay with it? 

> As per why zsh is used, that's because output redirection and wildcard expansion didn't work in bash/sh. For some reason `echo X > /sys/some/*/path` only works in zsh and not any other shell, at least from my testing.

Weird; wildcard expansion should be part of the POSIX standard. Either way this patch should remove all the wildcard expansion `echo` calls in the program, so `sh` should work now I believe.

**Comment by TheAlexDev23** [comment]
> I saw an error followed by a crash in the logs. This patch removed both the error and stopped the crash. I'm not 100% sure why this stopped the crashes, to be fair; I wonder if there's a weird subprocess interaction going on (maybe with systemd)?

Could you try to replicate this? Maybe by rolling back to before the commit where you fixed it, and send the crash logs? If systemd fails a process when a subprocess fails only on some systems, that might be a problem.

> Would it be worth pulling out the "write a value to a file" case into a separate method without requiring a subshell? This would help detect "file not existing" errors and keep the code cleaner in general (by not building bash strings and invoking subprocesses for writing files). I can work on this if you'd be okay with it?

That would've been the proper way to do that. You do risk cluttering the user's screen with overwhelming warnings but otherwise it provides more info and reduces points of failure. I did it through shell based commands because it's easier at first, and I wanted to get new features working quickly. Just by looking at the majority of these shell based write commands, replacing them with proper write functions should not add any extra complexity, especially because you got rid of most wildcard expansions. This might be a pain when trying to add new functions that rely on wildcards, but otherwise it would be a net benefit. But do note that there are almost 40 shell based sysfs writes, so it will be a lot of work.

Ultimately you're probably right on the fact that it will be better code-wise, and I'll merge if you're willing to replace them, but otherwise I'll hapily merge the changes that you've made previously. Tell me what you'd like to do.

> Weird; wildcard expansion should be part of the POSIX standard. Either way this patch should remove all the wildcard expansion echo calls in the program, so sh should work now I believe.

Wilcdard expansion does work afaik, it just works weird when mixed with output redirection through `echo X > /path/with/*/wilcard/`, I may be doing something wrong, but all wildcard based redirections only work in zsh for me. Altough, after your PR there shouldn't be any wildcard redirections, so getting rid of zsh for sh shouldn't be problem, just something to take into account in the future when trying to work with wildcards.

**Comment by ischeinkman** [comment]
> Could you try to replicate this? Maybe by rolling back to before the commit where you fixed it, and send the crash logs? If systemd fails a process when a subprocess fails only on some systems, that might be a problem.

Just tried it, and it seems I was mistaken; that extra check for `/online` isn't causing any changes. Removed. 

> Ultimately you're probably right on the fact that it will be better code-wise, and I'll merge if you're willing to replace them, but otherwise I'll hapily merge the changes that you've made previously. Tell me what you'd like to do.

I think for now it might be best to merge this in and then I can open different PRs for a) moving to `sh` and b) extracting out 1+ helper(s) for writing sysfs files (since it looks like we already have some for reads? That way we keep the PRs focused on single items?

**Comment by TheAlexDev23** [comment]
> I think for now it might be best to merge this in and then I can open different PRs for a) moving to sh and b) extracting out 1+ helper(s) for writing sysfs files (since it looks like we already have some for reads?). That way we keep the PRs focused on single items?

Sure!

**Pull request merged**
